config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :searches, only: [:new, :create]

  resources :gift_cards, only: [:new]

  root to: 'searches#new'
end

app/models/address.rb
class Address
  attr_reader :street, :city, :state

  def initialize(street:, city:, state:)
    @street = street
    @city = city
    @state = state
  end

  def formatted
    "#{street}, #{city}, #{state}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  has_many :reviews, dependent: :destroy

  def self.fetch(business_id)
    find_by(yelp_id: business_id) || create_new_from_api(business_id)
  end

  def address
    @address ||= Address.new(street: address_street, city: address_city, state: address_state)
  end

  private

  def self.create_new_from_api(business_id)
    business = fetch_from_api(business_id)
    transaction do
      business.reviews << fetch_reviews(business_id)
      business.save!
    end
    business
  end

  def self.fetch_from_api(business_id)
    api = YelpApi.new
    json = api.business_details(business_id)
    from_json json
  end

  def self.from_json(json)
    new.tap do |business|
      business.yelp_id = json['id']
      business.name = json['name']
      business.rating = json['rating']
      business.review_count = json['review_count']
      business.url = json['url']
      business.image_url = json['image_url']
      business.address_street = json['location']['address1']
      business.address_city = json['location']['city']
      business.address_state = json['location']['state']
      business.cross_streets = json['location']['cross_streets']
      business.latitude = json['coordinates']['latitude']
      business.longitude = json['coordinates']['longitude']
      business.phone_number = json['display_phone']
      business.categories = json['categories'].map { |c| c['title'] }
      business.neighborhood = json['neighborhood']
      business.price_range = json['price']
      business.raw_response = json
    end
  end

  def self.fetch_reviews(business_id)
    Review.fetch_from_api(business_id)
  end
end

app/models/gift_card.rb
class GiftCard
  attr_accessor :business

  def initialize(params)
    @business = params[:business]
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :business

  def self.fetch_from_api(business_id)
    api = YelpApi.new
    json = api.business_reviews(business_id)
    json['reviews'].map { |review_json| from_json(review_json) }
  end

  private

  def self.from_json(json)
    new.tap do |review|
      review.yelp_id = json['id']
      review.url = json['url']
      review.text = json['text']
      review.rating = json['rating']
      review.raw_response = json
    end
  end
end

app/models/search.rb
class Search
  attr_accessor :q, :latitude, :longitude, :area_name, :results

  def initialize(params)
    @q = params[:q]
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    @area_name = params[:area_name]
  end

  def perform
    api = YelpApi.new
    api.search query_params
    @results = api.result['businesses'].map { |business| SearchResult.new business }
  end


  private

  def query_params
    {
      term: @q,
      latitude: @latitude,
      longitude: @longitude,
      limit: 5
    }
  end
end

app/models/search_result.rb
class SearchResult
  attr_accessor :business_id, :name, :rating, :image_url,
    :address_street, :address_city, :address_state, :distance

  def initialize(params)
    @business_id = params['id']
    @name = params['name']
    @rating = params['rating']
    @image_url = params['image_url']
    @address_street = params['location']['address1']
    @address_city = params['location']['city']
    @address_state = params['location']['state']
    @distance = params['distance']
  end

  def address
    @address ||= Address.new(street: address_street, city: address_city, state: address_state)
  end
end

app/models/yelp_api.rb
require 'net/http'

class YelpApi
  class Error < StandardError; end;

  YELP_API_BASE_URL = 'https://api.yelp.com/v3'.freeze

  attr_accessor :result

  def initialize
    @yelp_api_key = ENV['YELP_API_KEY']
  end

  def search(query_params)
    uri = URI("#{YELP_API_BASE_URL}/businesses/search")
    uri.query = URI.encode_www_form(query_params)
    perform uri
  end

  def business_details(business_id)
    uri = URI("#{YELP_API_BASE_URL}/businesses/#{business_id}")
    perform uri
  end

  def business_reviews(business_id)
    uri = URI("#{YELP_API_BASE_URL}/businesses/#{business_id}/reviews")
    perform uri
  end


  private

  attr_reader :yelp_api_key, :response

  def perform(uri)
    request = Net::HTTP::Get.new(uri)
    request['Authorization'] = "Bearer #{yelp_api_key}"

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    begin
      @response = http.request(request)
    rescue Exception => e
      Rails.logger.error("Error searching Yelp API, #{e.class} - #{e.message}")
    end

    handle_response
  end

  def handle_response
    if response.code == '200'
      @result = JSON.parse(response.body)
    else
      raise Error.new json['error']['description']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gift_cards_controller.rb
class GiftCardsController < ApplicationController
  def new
    business = Business.fetch(params[:business_id])
    @gift_card = GiftCard.new(business: business)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @businesses = Business.all
  end

  def create
    @search = Search.new(search_params)
    begin
      @search.perform
    rescue YelpApi::Error => e
      flash[:error] = e.message
      render 'new'
    end
  end


  private

  def search_params
    params.require(:search).permit(:q, :latitude, :longitude, :area_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def rating_image_for(rating)
    if rating % 1 > 0
      path = "yelp_stars/small_#{rating.to_i}_half.png"
    else
      path = "yelp_stars/small_#{rating.to_i}.png"
    end
    image_tag path, class: 'yelp-rating-stars'
  end

  def miles_away(meters)
    miles = meters / 1609.344
    content_tag :span, "#{miles.round(1)} miles away", class: 'miles-away'
  end
end

app/helpers/business_helper.rb
module BusinessHelper
  def formatted_price_range(price_range)
    case price_range.length
    when 1
      content_tag(:span, price_range, class: 'text-green') +
        content_tag(:span, '$$$', class: 'text-light') +
        content_tag(:span, 'under $10')
    when 2
      content_tag(:span, price_range, class: 'text-green') +
        content_tag(:span, '$$', class: 'text-light') +
        content_tag(:span, ' $11-30')
    when 3
      content_tag(:span, price_range, class: 'text-green') +
        content_tag(:span, '$', class: 'text-light') +
        content_tag(:span, ' $31-60')
    when 4
      content_tag(:span, price_range, class: 'text-green') +
        content_tag(:span, ' above $61')
    end
  end

  def category_links(categories)
    links = categories.map do |category|
      link_to category, '#'
    end

    safe_join links, ', '
  end

  def similar_business_links(business)
    links = business.categories.map do |category|
      content_tag :div, class: 'similar-business-category-link' do
        link_to "#{category} in #{business.address_city}"
      end
    end

    content_tag :div, id: 'similar-business-links' do
      safe_join links
    end
  end
end

app/views/businesses/_business.html.erb
<div class="business">
  <div class="business-image" style="margin: 0 auto 8px;">
    <div class="image-crop">
      <%= image_tag business.image_url, height: 120, width: 120 %>
    </div>
  </div>

  <div class="search-result-details">
    <h5><%= business.name %></h5>

    <%= rating_image_for(business.rating) %>

    <div class="search-result-address">
      <%= business.address.formatted %>
    </div>

    <div class="search-result-purchase-link">
      <%= link_to 'Purchase Giftly gift card',
        new_gift_card_path(business_id: business.yelp_id) %>
    </div>
  </div>

  <div class="clearfix"></div>
</div>

app/views/gift_cards/new.html.erb
<% content_for :breadcrumbs do %>
  <%= link_to 'Gift Cards' %>
  <span class="breadcrumb-separator">&gt;</span>
  <%= link_to @gift_card.business.address_city %>
  <span class="breadcrumb-separator">&gt;</span>
  <%= link_to @gift_card.business.categories.first %>
  <span class="breadcrumb-separator">&gt;</span>
  <%= link_to @gift_card.business.name %>
<% end %>

<div class="body-card body-card-first">
  <div class="body-card-title">
    <h1 id="buy-title">Buy a Gift Card to <%= @gift_card.business.name %></h1>
  </div>

  <p>
    Send a personalized cash gift card that is suggested for use at
    <span class="business-name"><%= @gift_card.business.name %></span>. Any
    amount up to $1,000. Deliver by email, mail, or print at home.
  </p>
  <p>
    You suggest where to go and what to get - the recipient always gets what
    they want.
  </p>

  <p>
    <%= link_to 'Customize &amp; Buy »'.html_safe, '#', id: 'buy-button', class: 'btn btn-primary' %>
  </p>

  <div id="satisfaction-guarantee">
    <%= link_to '#' do %>
      <%= image_tag 'giftly-guarantee.png' %> 100% satisfaction guaranteed
    <% end %>
  </div>

  <div class="body-card-footer">
    <div class="body-card-footer-column first-column">
      <%= link_to 'How it works' %>
    </div>
    <div class="body-card-footer-column">
      <%= link_to 'Sample gift' %>
    </div>
    <div class="body-card-footer-column last-column">
      <%= link_to 'Why Giftly' %>
    </div>
  </div>
</div>

<div class="body-card text-center">
  <div class="body-card-title">
    <h2>Customizable greeting cards available for every occasion</h2>
  </div>

  <%= image_tag 'happy-birthday-greeting-card.png' %>
  <%= image_tag 'enjoy-greeting-card.png' %>
  <%= image_tag 'congrats-greeting-card.png' %>
  <%= image_tag 'photo-greeting-card.png' %>
  <%= image_tag 'love-greeting-card.png' %>
  <%= image_tag 'happy-birthday-candles-greeting-card.png' %>
</div>

<div class="body-card">
  <div class="body-card-title">
    <h2>About <%= @gift_card.business.name %></h2>
  </div>

  <div class="business-profile">
    <div class="business-image">
      <div class="image-crop">
        <%= image_tag @gift_card.business.image_url, height: 120, width: 120 %>
      </div>
    </div>
    <div class="business-details">
      <h4><%= @gift_card.business.name %></h4>
      <div class="business-rating">
        <%= rating_image_for(@gift_card.business.rating) %>
        <span class="business-ratings-description">
          based on <%= @gift_card.business.review_count %> reviews on
          <%= image_tag 'yelp_logo_small.png', class: 'yelp-logo-small' %>
      </div>
      <div class="business-address">
        <%= @gift_card.business.address.formatted %>
      </div>
      <div class="business-phone-number">
        <%= @gift_card.business.phone_number %>
      </div>
    </div>
  </div>

  <div class="business-extras">
    <div class="business-categories">
      <h5>Categories</h5>
      <%= category_links @gift_card.business.categories %>
    </div>
    <div class="business-price-range">
      <h5>Price Range</h5>
      <%= formatted_price_range(@gift_card.business.price_range) %>
    </div>
    <div class="business-cross-streets">
      <h5>Cross Streets</h5>
      <%= @gift_card.business.cross_streets %>
    </div>
  </div>

  <div id="business-map">
  </div>

  <div class="business-reviews">
    <h4>
      <%= image_tag 'yelp_logo_medium.png', class: 'yelp-reviews-logo' %>
      reviews for <%= @gift_card.business.name %>
    </h4>
    <%= render @gift_card.business.reviews %>
  </div>

  <div class="body-card-footer">
    <div class="body-card-footer-column">
      Is this your business? Take a moment to
      <%= link_to 'claim this page' %> and customize it for free.
    </div>
  </div>
</div>

<div class="body-card">
  <div class="body-card-title">
    <h2>If not <%= @gift_card.business.name %>, they might also enjoy</h2>
  </div>

  <h5>Browse places similar to <%= @gift_card.business.name %></h5>

  <%= similar_business_links(@gift_card.business) %>

  <h5>Or perhaps,</h5>
  <div class="other-gift-options">
    <div class="other-gift-options-restaurant">
      <%= image_tag 'dinner-at-any-restaurant.png' %>
      Dinner at Any Restaurant
    </div>
    <div class="other-gift-options-any">
      <%= image_tag 'anything-at-anyplace.png' %>
      Anything at Any Place
    </div>
    <div class="other-gift-options-movies">
      <%= image_tag 'movies-at-any-theater.png' %>
      Movies at Any Theater
    </div>
  </div>

  <p>
    <%= link_to 'Browser more gift ideas' %>
  </p>
</div>

<div class="body-card">
  <div class="body-card-title">
    <h2>Why buy a gift card using <%= image_tag 'giftly-small-white.png' %>?</h2>
  </div>

  <p>
    Giftly makes it easy to send a gift card that's personal, but also flexible
    and convenient. It's the perfect last minute gift for a birthday, graduation,
    wedding, holiday, and more.
  </p>

  <p>
    Give any amount up to $1,000 and suggest any business, item, or experience
    you think the recipient will enjoy. Deliver in a customized greeting card or
    e-greeting card.
  </p>

  <p>
    Gifts can be sent electronically by email or text¹ , printed at home, or
    delivered in the mail.
  </p>

  <p>
    Your recipient redeems online and chooses how to receive the money. They can
    spend their funds at <span class="business-name"><%= @gift_card.business.name %></span>,
    or elsewhere if they prefer. There is no physical gift certificate to carry
    around or lose.
  </p>

  <p>
    Gift cards sent through Giftly never expire and there are no fees, so
    recipients can redeem at any time.
  </p>

  <p>
    Giftly combines the flexibility and convenience of giving money, but
    includes a thoughtful suggestion that makes it more personal.
  </p>

  <p>
    <%= link_to 'See an example gift »', '#', class: 'btn btn-link', id: 'example-gift-button' %>
  </p>
</div>

<div class="body-card">
  <div class="body-card-title">
    <h2>Help</h2>
  </div>

  <p>
    If you have questions, need help, or want to modify, resend, or cancel a
    gift, please see our <%= link_to 'Support Center' %>, where you can access an array of self-service tools and our FAQ.
  </p>

  <p>
    <%= link_to '#' do %>
      <%= image_tag 'giftly-guarantee.png' %> 100% satisfaction guaranteed
    <% end %>
  </p>
</div>

<div class="body-card">
  <div class="body-card-title">
    <h2>Gift Card Disclosure</h2>
  </div>

  <p>
    The Giftly Gift Card is redeemed for money through the Giftly website. It is
    not accepted by any third-party merchant and is not covered by the CARD Act.
    Giftly Gift Cards never expire and there are no inactivity fees.  Please see
    the <%= link_to 'Terms and Conditions' %> for the complete terms.
  </p>
</div>

<script type="text/javascript">
  var map, marker;
  var coordinates = {
    lat: <%= @gift_card.business.latitude %>,
    lng: <%= @gift_card.business.longitude %>
  };

  function googleInit() {
    map = new google.maps.Map(document.getElementById('business-map'), {
      center: coordinates,
      zoom: 17,
      disableDefaultUI: true,
      draggable: false,
      draggableCursor: 'arrow'
    });
    marker = new google.maps.Marker({ position: coordinates, map: map });
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftlyChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.typekit.net/qso2bkv.css">
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div id="breadcrumb-nav">
      <%= yield :breadcrumbs %>
    </div>

    <div class="container">
      <section id="main-content">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
      </section>
    </div>
  </body>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GCP_API_KEY'] %>&callback=googleInit" type="text/javascript"></script>

</html>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating">
    <%= rating_image_for(review.rating) %>
  </div>
  <p class="review-text">
    <%= review.text %>
    <%= link_to 'read more', review.url %>
  </p>
</div>

app/views/searches/_search_result.html.erb
<div class="search-result text-center">
  <div class="business-image float-left">
    <div class="image-crop">
      <%= image_tag search_result.image_url, height: 120, width: 120 %>
    </div>
  </div>

  <div class="search-result-details">
    <h5><%= search_result.name %></h5>

    <%= rating_image_for(search_result.rating) %>

    <div class="search-result-address">
      <%= search_result.address.formatted %>
    </div>

    <div class="search-result-distance">
      <%= miles_away(search_result.distance) %>
    </div>

    <div class="search-result-purchase-link">
      <%= link_to 'Purchase Giftly gift card',
        new_gift_card_path(business_id: search_result.business_id) %>
    </div>
  </div>

  <div class="clearfix"></div>
</div>

app/views/searches/create.html.erb
<% content_for :page_title, 'Business search' %>

<div class="body-card body-card-first text-center">
  <div class="body-card-title">
    <h1>Search results for “<%= @search.q %>”</h1>
    <h2>Near <%= @search.area_name %></h1>
  </div>

  <h4>Showing <%= pluralize @search.results.size, 'result' %></h4>
  <div id="search-results">
    <% @search.results.each do |result| %>
      <%= render partial: 'search_result', locals: { search_result: result } %>
    <% end %>
  </div>
</div>

app/views/searches/new.html.erb
<div class="body-card body-card-first text-center">
  <div class="body-card-title">
    <h1>Give a Giftly gift card.</h1>
  </div>

  <div id="search-form">
    <%= form_for :search, url: searches_path do |f| %>
      <%= f.hidden_field :latitude %>
      <%= f.hidden_field :longitude %>
      <%= f.hidden_field :area_name %>

      <div class="form-group">
        <%= f.label :q, 'Search for a business to gift...' %>
        <%= f.text_field :q, class: 'form-control' %>
        <small id="search-location" class="form-text text-muted">Finding current location...</small>
      </div>

      <%= f.submit 'Please wait...',
        id: 'search-submit',
        class: 'btn btn-primary',
        disabled: true %>
    <% end %>
  </div>
</div>

<div class="body-card text-center">
  <div class="body-card-title">
    <h1>Browse some of our favorites!</h1>
  </div>

  <div id="saved-businesses">
    <%= render @businesses %>
  </div>
</div>

<script type="text/javascript">
  var latitudeField = document.getElementById('search_latitude');
  var longitudeField = document.getElementById('search_longitude');
  var areaNameField = document.getElementById('search_area_name');
  var submitButton = document.getElementById('search-submit');
  var helpText = document.getElementById('search-location');
  var geocoder;

  function googleInit() {
    geocoder = new google.maps.Geocoder();
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(positionSuccess)
    } else {
      helpText.innerHTML = 'Please allow geolocation in order to search';
    }
  }

  function positionSuccess(position) {
    latitudeField.value = position.coords.latitude;
    longitudeField.value = position.coords.longitude;

    getAreaName(position.coords.latitude, position.coords.longitude);
  }

  function getAreaName(lat, lng) {
    var latLng = new google.maps.LatLng(lat, lng);

    geocoder.geocode({ 'latLng': latLng }, function(results, status) {
      if(status == google.maps.GeocoderStatus.OK) {
        var area = results.filter(function(address) {
          return address.types.includes('locality');
        })[0];

        areaSuccess(area.formatted_address);
      } else {
        areaFailure();
      }
    });
  }

  function areaSuccess(areaName) {
    areaNameField.value = areaName;
    helpText.innerHTML = 'Search businesses near ' + areaName;

    enableSearch();
  }

  function areaFailure() {
    enableSearch();
  }

  function enableSearch() {
    submitButton.removeAttribute('disabled');
    submitButton.value = 'Search »';
  }
</script>

app/views/shared/_flash_messages.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <%= content_tag :div, class: "alert alert-#{key}", role: 'alert' do %>
      <%= value %>
    <% end %>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light" id="main-nav">
  <a class="navbar-brand" href="/">
    <%= link_to image_tag('giftly-logo-header.png'), root_path %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <span class="navbar-text">
      <%= yield :page_title %>
    </span>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'New Search', new_search_path, class: 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Browse</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Corporate Gifts</a>
      </li>
    </ul>
  </div>
</nav>